import 'package:flutter_test/flutter_test.dart';
import 'package:grader/grading.dart';
import 'package:grader/keyfile.dart';
import 'package:grader/qr_scan.dart';
import 'package:grader/select.dart';

const keyJson = '''
{
  "version": 1,
  "exam_title": "Sample Exam",
  "source_fingerprint": "ab12cd34",
  "options_per_question": 4,
  "sections": {"easy": 3, "medium": 3, "hard": 2},
  "answer_key": [1, 2, 2, 1, 0, 2, 1, 1]
}
''';

void main() {
  final key = AnswerKey.parse(keyJson);
  final payload = QrPayload.decode('v1|1|424242|2|2|1|ab12cd34');

  VariantPlan planFor(QrPayload p) => buildVariant(
    seed: p.seed,
    sectionSizes: key.sections,
    counts: p.counts,
    optionsPerQuestion: key.optionsPerQuestion,
  );

  List<int> correctMarks(VariantPlan plan) => [
    for (final q in plan.sheet)
      q.optionPerm.indexOf(key.answerKey[q.globalIndex]),
  ];

  test('grade against fixture-anchored, hand-derived marks (seed 0)', () {
    // Anchored in shared/test-vectors.json, seed-0 variant case (generated by
    // the PYTHON implementation, so this is independent of buildVariant here):
    //   sections {easy:5, medium:4, hard:3}, counts {easy:2, medium:2, hard:1}
    //   selections: easy=[2,3], medium=[2,1], hard=[0]
    //   sheet global indices: [2, 3, 5+2=7, 5+1=6, 9+0=9]
    //   perms: r0=[3,0,1,2] r1=[2,1,0,3] r2=[1,2,0,3] r3=[3,2,1,0] r4=[3,2,0,1]
    // With the literal answer key below (12 entries), the answers at those
    // globals are [2, 1, 1, 1, 1], so the correct bubble positions are:
    //   r0: perm.indexOf(2)=3, r1: indexOf(1)=1, r2: 0, r3: 2, r4: 3
    // -> hardcoded marks [3,1,0,2,3] must score 5/5; flipping r4 scores 4/5.
    const anchoredKeyJson = '''
    {
      "version": 1,
      "exam_title": "T",
      "source_fingerprint": "fp012345",
      "options_per_question": 4,
      "sections": {"easy": 5, "medium": 4, "hard": 3},
      "answer_key": [1, 2, 2, 1, 0, 2, 1, 1, 0, 1, 2, 0]
    }
    ''';
    final anchoredKey = AnswerKey.parse(anchoredKeyJson);
    final anchoredPayload = QrPayload.decode('v1|1|0|2|2|1|fp012345');

    final full = grade(
      key: anchoredKey,
      payload: anchoredPayload,
      marks: const [3, 1, 0, 2, 3],
    );
    expect(full.score, 5);
    expect(full.total, 5);
    expect([for (final q in full.perQuestion) q.globalIndex], [2, 3, 7, 6, 9]);
    expect(
      [for (final q in full.perQuestion) q.correctPosition],
      [3, 1, 0, 2, 3],
    );

    final oneWrong = grade(
      key: anchoredKey,
      payload: anchoredPayload,
      marks: const [3, 1, 0, 2, 0],
    );
    expect(oneWrong.score, 4);
    expect(
      [for (final q in oneWrong.perQuestion) q.correct],
      [true, true, true, true, false],
    );
  });

  test('empty sheet (all-zero counts) grades to 0/0 without error', () {
    final zeroPayload = QrPayload.decode('v1|1|424242|0|0|0|ab12cd34');
    final result = grade(key: key, payload: zeroPayload, marks: const []);
    expect(result.score, 0);
    expect(result.total, 0);
    expect(result.perQuestion, isEmpty);
  });

  test('round trip: all-correct marks score full', () {
    final result = grade(
      key: key,
      payload: payload,
      marks: correctMarks(planFor(payload)),
    );
    expect(result.score, 5);
    expect(result.total, 5);
    expect(result.perQuestion.every((q) => q.correct), isTrue);
  });

  test('round trip: alternating wrong marks score the expected pattern', () {
    final plan = planFor(payload);
    final correct = correctMarks(plan);
    final marks = <int?>[
      for (var row = 0; row < plan.sheet.length; row++)
        row.isEven ? correct[row] : (correct[row] + 1) % 4,
    ];
    final result = grade(key: key, payload: payload, marks: marks);
    expect(
      [for (final q in result.perQuestion) q.correct],
      [true, false, true, false, true],
    );
    expect(result.score, 3);
  });

  test('unanswered (null) marks count as incorrect but are reported', () {
    final marks = List<int?>.filled(5, null);
    final result = grade(key: key, payload: payload, marks: marks);
    expect(result.score, 0);
    expect(result.perQuestion.every((q) => q.markedPosition == null), isTrue);
  });

  test('fingerprint mismatch is flagged, not graded', () {
    final other = QrPayload.decode('v1|1|424242|2|2|1|deadbeef');
    expect(
      () => grade(key: key, payload: other, marks: List<int?>.filled(5, 0)),
      throwsA(
        isA<GradingException>().having(
          (e) => e.message,
          'message',
          contains('fingerprint'),
        ),
      ),
    );
  });

  test('marks length mismatch is flagged', () {
    expect(
      () => grade(key: key, payload: payload, marks: [0, 1]),
      throwsA(
        isA<GradingException>().having(
          (e) => e.message,
          'message',
          contains('marks'),
        ),
      ),
    );
  });

  test('payload counts exceeding key sections are flagged', () {
    final tooMany = QrPayload.decode('v1|1|424242|9|2|1|ab12cd34');
    expect(
      () => grade(key: key, payload: tooMany, marks: List<int?>.filled(12, 0)),
      throwsA(isA<GradingException>()),
    );
  });

  test('mark position outside the option range is flagged', () {
    expect(
      () => grade(key: key, payload: payload, marks: [0, 1, 2, 3, 4]),
      throwsA(
        isA<GradingException>().having(
          (e) => e.message,
          'message',
          contains('position'),
        ),
      ),
    );
  });
}
