"""Regenerate shared/test-vectors.json from the Python reference implementation.

Run deliberately, from generator/:  ../.venv/bin/python scripts/make_test_vectors.py
Changing the vectors changes the cross-language contract: the Dart side must be
updated to match and the QR payload version must be bumped (v1 -> v2).

All 64-bit values are decimal strings (JSON-number-safe for every parser).
"""

import json
from pathlib import Path

from mcexam.rng import SplitMix64
from mcexam.select import build_variant

RAW_SEEDS = [0, 1, 42, 123456789, 2**64 - 1]

VARIANT_CASES = [
    {
        "seed": 0,
        "sections": {"easy": 5, "medium": 4, "hard": 3},
        "counts": {"easy": 2, "medium": 2, "hard": 1},
        "m": 4,
    },
    {
        "seed": 1,
        "sections": {"easy": 5, "medium": 4, "hard": 3},
        "counts": {"easy": 5, "medium": 4, "hard": 3},
        "m": 4,
    },
    {
        "seed": 424242,
        "sections": {"easy": 30, "medium": 25, "hard": 15},
        "counts": {"easy": 10, "medium": 8, "hard": 2},
        "m": 5,
    },
    {
        "seed": 2**64 - 1,
        "sections": {"easy": 10, "medium": 10, "hard": 10},
        "counts": {"easy": 3, "medium": 3, "hard": 3},
        "m": 6,
    },
    {
        "seed": 987654321987654321,
        "sections": {"easy": 2, "medium": 2, "hard": 2},
        "counts": {"easy": 0, "medium": 1, "hard": 2},
        "m": 2,
    },
]


def main() -> None:
    vectors = {
        "comment": "Cross-language determinism fixture. Generated by"
        " generator/scripts/make_test_vectors.py; do not edit by hand."
        " 64-bit values are decimal strings.",
        "splitmix64": [],
        "variants": [],
    }
    for seed in RAW_SEEDS:
        rng = SplitMix64(seed)
        vectors["splitmix64"].append(
            {"seed": str(seed), "first5": [str(rng.next_uint64()) for _ in range(5)]}
        )
    for case in VARIANT_CASES:
        plan = build_variant(case["seed"], case["sections"], case["counts"], case["m"])
        vectors["variants"].append(
            {
                "seed": str(case["seed"]),
                "sections": case["sections"],
                "counts": case["counts"],
                "options_per_question": case["m"],
                "expected": {
                    "selections": {k: list(v) for k, v in plan.selections.items()},
                    "option_perms": [list(sq.option_perm) for sq in plan.sheet],
                },
            }
        )
    out = Path(__file__).resolve().parents[2] / "shared" / "test-vectors.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(vectors, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
